import { MigrationInterface, QueryRunner } from 'typeorm';

/**
 * Initial schema: 30 tables covering organizations, users, students, teachers,
 * classes, subjects, academic years and terms, enrollments, teacher assignments,
 * assessments, marks, results, report card remarks, fees, payments, fines,
 * sibling discounts, attendance (student + staff), correction requests,
 * notifications, guardian contacts, principal alerts, audit logs and roles.
 *
 * Column names match the TypeORM entity property names (camelCase) because the
 * entities do not override them with an explicit `name`.
 */
export class InitialSchema1790899200000 implements MigrationInterface {
  name = 'InitialSchema1790899200000';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`CREATE EXTENSION IF NOT EXISTS "uuid-ossp"`);
    await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organization_id" uuid, "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "email" character varying NOT NULL, "passwordHash" character varying(255) NOT NULL, "firstName" character varying NOT NULL, "lastName" character varying NOT NULL, "role" character varying(20) NOT NULL, "isEmailVerified" boolean NOT NULL DEFAULT true, "refreshToken" character varying(255), "resetPasswordToken" character varying(50), "resetPasswordExpires" TIMESTAMP, CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
    await queryRunner.query(`CREATE TABLE "terms" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organization_id" uuid, "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "name" character varying NOT NULL, "order" integer NOT NULL, "academicYearId" uuid, CONSTRAINT "PK_33b6fe77d6ace7ff43cc8a65958" PRIMARY KEY ("id"))`);
    await queryRunner.query(`CREATE TABLE "academic_years" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organization_id" uuid, "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "name" character varying NOT NULL, "isCurrent" boolean NOT NULL, CONSTRAINT "PK_2021b90bfbfa6c9da7df34ca1cf" PRIMARY KEY ("id"))`);
    await queryRunner.query(`CREATE TABLE "results" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organization_id" uuid, "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "obtainedMarks" numeric(5,2) NOT NULL, "percentage" numeric(5,2) NOT NULL, "grade" character varying(2) NOT NULL, "isPassed" boolean NOT NULL, "subjectAverage" numeric(5,2) NOT NULL, "classAverage" numeric(5,2) NOT NULL, "studentId" uuid, "subjectId" uuid, "assessmentId" uuid, CONSTRAINT "PK_e8f2a9191c61c15b627c117a678" PRIMARY KEY ("id"))`);
    await queryRunner.query(`CREATE TABLE "assessments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organization_id" uuid, "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "name" character varying NOT NULL, "type" character varying NOT NULL, "maximumMarks" numeric(5,2) NOT NULL, "passingMarks" numeric(5,2) NOT NULL, "examDate" TIMESTAMP NOT NULL, "status" character varying(50) NOT NULL DEFAULT 'Draft', "isPublished" boolean NOT NULL DEFAULT false, "classId" uuid, "subjectId" uuid, "academicYearId" uuid, "termId" uuid, CONSTRAINT "PK_a3442bd80a00e9111cefca57f6c" PRIMARY KEY ("id"))`);
    await queryRunner.query(`CREATE TABLE "subjects" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organization_id" uuid, "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "name" character varying NOT NULL, "code" character varying(10), "classId" uuid, "teacherId" uuid, CONSTRAINT "PK_1a023685ac2b051b4e557b0b280" PRIMARY KEY ("id"))`);
    await queryRunner.query(`CREATE TABLE "marks" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organization_id" uuid, "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "obtainedMarks" numeric(5,2) NOT NULL, "isAbsent" boolean NOT NULL, "studentId" uuid, "subjectId" uuid, "assessmentId" uuid, CONSTRAINT "PK_051deeb008f7449216d568872c6" PRIMARY KEY ("id"))`);
    await queryRunner.query(`CREATE TABLE "fee_structures" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organization_id" uuid, "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "name" character varying NOT NULL, "amount" numeric(10,2) NOT NULL, "frequency" character varying(50) NOT NULL, CONSTRAINT "PK_d634078deb9cf5ceb5788ad9b53" PRIMARY KEY ("id"))`);
    await queryRunner.query(`CREATE TABLE "payments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organization_id" uuid, "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "amount" numeric(10,2) NOT NULL, "paymentMethod" character varying NOT NULL, "transactionId" character varying NOT NULL, "paymentDate" date NOT NULL, "receiptNumber" text, "feeId" uuid, "processedById" uuid, CONSTRAINT "PK_197ab7af18c93fbb0c9b28b4a59" PRIMARY KEY ("id"))`);
    await queryRunner.query(`CREATE TABLE "fees" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organization_id" uuid, "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "amount" numeric(10,2) NOT NULL, "originalAmount" numeric(10,2), "discountAmount" numeric(10,2) NOT NULL DEFAULT '0', "paidAmount" numeric(10,2) NOT NULL, "dueDate" TIMESTAMP NOT NULL, "isPaid" boolean NOT NULL DEFAULT false, "paymentDate" date, "challanNumber" character varying(100), "paymentMode" text, "transactionId" text, "studentId" uuid, "feeStructureId" uuid, CONSTRAINT "PK_97f3a1b1b8ee5674fd4da93f461" PRIMARY KEY ("id"))`);
    await queryRunner.query(`CREATE TABLE "students" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organization_id" uuid, "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "admissionNumber" character varying NOT NULL, "name" character varying NOT NULL, "fatherGuardianName" character varying(100), "dateOfBirth" TIMESTAMP NOT NULL, "gender" character varying NOT NULL, "contactInformation" character varying(50) NOT NULL, "className" character varying(20), "section" character varying(10), "admissionDate" date, "status" boolean NOT NULL DEFAULT true, "userId" uuid, CONSTRAINT "UQ_e940f48d8a6da23b7e6308770be" UNIQUE ("contactInformation"), CONSTRAINT "PK_7d7f07271ad4ce999880713f05e" PRIMARY KEY ("id"))`);
    await queryRunner.query(`CREATE TABLE "student_enrollments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organization_id" uuid, "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "academicYear" character varying(20) NOT NULL, "term" character varying(20) NOT NULL, "isCurrent" boolean NOT NULL DEFAULT true, "studentId" uuid, "classId" uuid, CONSTRAINT "PK_65f64fb270d4575b099b16e00a2" PRIMARY KEY ("id"))`);
    await queryRunner.query(`CREATE TABLE "classes" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organization_id" uuid, "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "name" character varying NOT NULL, "section" character varying(20) NOT NULL, "academicYear" character varying NOT NULL, CONSTRAINT "PK_e207aa15404e9b2ce35910f9f7f" PRIMARY KEY ("id"))`);
    await queryRunner.query(`CREATE TABLE "teacher_assignments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organization_id" uuid, "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "isClassIncharge" boolean NOT NULL DEFAULT true, "teacherId" uuid, "classId" uuid, "subjectId" uuid, CONSTRAINT "PK_49fabd5cfe8fa2beb47a0b0fed9" PRIMARY KEY ("id"))`);
    await queryRunner.query(`CREATE TABLE "teachers" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organization_id" uuid, "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "firstName" character varying NOT NULL, "lastName" character varying NOT NULL, "employeeId" character varying(20) NOT NULL, "hireDate" date, "userId" uuid, CONSTRAINT "UQ_a25d4cc612f7cf5abb45d37cfa1" UNIQUE ("employeeId"), CONSTRAINT "PK_a8d4f83be3abe4c687b0a0093c8" PRIMARY KEY ("id"))`);
    await queryRunner.query(`CREATE TABLE "organizations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organization_id" uuid, "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "name" character varying NOT NULL, "logo" character varying(255), "address" text, "phone" character varying(20), "email" character varying(100), "academicYear" character varying(20), "currentTerm" character varying(20) NOT NULL DEFAULT 'Term 1', "attendanceGranularity" character varying(20) NOT NULL DEFAULT 'daily', "attendanceLockDays" integer NOT NULL DEFAULT '2', "staffAttendanceMode" character varying(30) NOT NULL DEFAULT 'admin_marked', "classPassDropAlertPercent" numeric(5,2) NOT NULL DEFAULT '10', "attendanceAlertPercent" numeric(5,2) NOT NULL DEFAULT '75', "feeCollectionTargetPercent" numeric(5,2) NOT NULL DEFAULT '80', "status" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_6b031fcd0863e3f6b44230163f9" PRIMARY KEY ("id"))`);
    await queryRunner.query(`CREATE TABLE "notification_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organization_id" uuid, "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "triggerType" character varying(40) NOT NULL, "messageBody" text NOT NULL, "recipientNumber" character varying(30) NOT NULL, "status" character varying(20) NOT NULL DEFAULT 'QUEUED', "sentAt" TIMESTAMP, "retryCount" integer NOT NULL DEFAULT '0', "failureReason" text, "studentId" uuid, CONSTRAINT "PK_19c524e644cdeaebfcffc284871" PRIMARY KEY ("id"))`);
    await queryRunner.query(`CREATE TABLE "guardian_contacts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organization_id" uuid, "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "phoneNumber" character varying(30) NOT NULL, "isPrimary" boolean NOT NULL DEFAULT false, "studentId" uuid NOT NULL, CONSTRAINT "PK_e39a61c1da46a9c78a1cfccb7bd" PRIMARY KEY ("id"))`);
    await queryRunner.query(`CREATE TABLE "marks_correction_requests" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organization_id" uuid, "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "oldValue" numeric(5,2) NOT NULL, "requestedValue" numeric(5,2) NOT NULL, "reason" text NOT NULL, "status" character varying(20) NOT NULL DEFAULT 'PENDING', "reviewedAt" TIMESTAMP, "reviewReason" text, "markId" uuid NOT NULL, "requestedById" uuid NOT NULL, "reviewedById" uuid, CONSTRAINT "PK_bb7debb8c72c140e8713f935e10" PRIMARY KEY ("id"))`);
    await queryRunner.query(`CREATE TABLE "principal_alerts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organization_id" uuid, "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "alertType" character varying(50) NOT NULL, "title" character varying(100) NOT NULL, "message" text NOT NULL, "detailUrl" character varying(255) NOT NULL, "fingerprint" character varying(255) NOT NULL, "acknowledged" boolean NOT NULL DEFAULT false, "acknowledgedById" uuid, CONSTRAINT "PK_be278755db83f13908453e023c3" PRIMARY KEY ("id"))`);
    await queryRunner.query(`CREATE TABLE "report_card_remarks" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organization_id" uuid, "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "remarkText" text NOT NULL, "studentId" uuid NOT NULL, "termId" uuid NOT NULL, "enteredById" uuid NOT NULL, CONSTRAINT "UQ_f98ef7d3669fd669b54949cd0aa" UNIQUE ("organization_id", "studentId", "termId"), CONSTRAINT "PK_37cf87f3851c617540cedd76550" PRIMARY KEY ("id"))`);
    await queryRunner.query(`CREATE TABLE "sibling_discounts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organization_id" uuid, "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "discountType" character varying(20) NOT NULL, "value" numeric(10,2) NOT NULL, "studentId" uuid NOT NULL, CONSTRAINT "PK_47d743ff76293505a2148dee374" PRIMARY KEY ("id"))`);
    await queryRunner.query(`CREATE TABLE "fee_fines" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organization_id" uuid, "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "fineType" character varying(20) NOT NULL, "value" numeric(10,2) NOT NULL, "gracePeriodDays" integer NOT NULL DEFAULT '0', "feeId" uuid NOT NULL, CONSTRAINT "PK_54f43757fb18c483d80d19bdb78" PRIMARY KEY ("id"))`);
    await queryRunner.query(`CREATE TABLE "staff_leave_requests" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organization_id" uuid, "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "startDate" date NOT NULL, "endDate" date NOT NULL, "reason" text NOT NULL, "status" character varying(20) NOT NULL DEFAULT 'PENDING', "staffId" uuid NOT NULL, "approvedById" uuid, CONSTRAINT "PK_066c3ab8534c6675f094d717d2f" PRIMARY KEY ("id"))`);
    await queryRunner.query(`CREATE TABLE "attendance_records" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organization_id" uuid, "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "status" character varying(20) NOT NULL DEFAULT 'PRESENT', "markedAt" TIMESTAMP NOT NULL, "sessionId" uuid, "studentId" uuid NOT NULL, "markedById" uuid NOT NULL, CONSTRAINT "UQ_151f0c6b625a55932fe27d05158" UNIQUE ("sessionId", "studentId"), CONSTRAINT "PK_946920332f5bc9efad3f3023b96" PRIMARY KEY ("id"))`);
    await queryRunner.query(`CREATE TABLE "attendance_sessions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organization_id" uuid, "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "attendanceDate" date NOT NULL, "period" character varying(50), "locked" boolean NOT NULL DEFAULT false, "classId" uuid NOT NULL, "createdById" uuid NOT NULL, CONSTRAINT "UQ_66da5652f8670dd1514fd83ea25" UNIQUE ("organization_id", "classId", "attendanceDate", "period"), CONSTRAINT "PK_84d565d9e484e2bcdaf4a9e1890" PRIMARY KEY ("id"))`);
    await queryRunner.query(`CREATE TABLE "staff_attendance_records" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organization_id" uuid, "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "attendanceDate" date NOT NULL, "status" character varying(20) NOT NULL, "approved" boolean NOT NULL DEFAULT true, "staffId" uuid NOT NULL, "markedById" uuid NOT NULL, CONSTRAINT "UQ_37add854d05aa1036947b590379" UNIQUE ("organization_id", "staffId", "attendanceDate"), CONSTRAINT "PK_1c584ebb491d80bebdfd96398fb" PRIMARY KEY ("id"))`);
    await queryRunner.query(`CREATE TABLE "attendance_correction_requests" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organization_id" uuid, "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "oldStatus" character varying(20) NOT NULL, "requestedStatus" character varying(20) NOT NULL, "reason" text NOT NULL, "status" character varying(20) NOT NULL DEFAULT 'PENDING', "reviewedAt" TIMESTAMP, "reviewReason" text, "recordId" uuid NOT NULL, "requestedById" uuid NOT NULL, "reviewedById" uuid, CONSTRAINT "PK_bc2c64345b6fec38bcf0d0f5e36" PRIMARY KEY ("id"))`);
    await queryRunner.query(`CREATE TABLE "roles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "description" text, "permissionBits" integer NOT NULL DEFAULT '0', CONSTRAINT "UQ_648e3f5447f725579d7d4ffdfb7" UNIQUE ("name"), CONSTRAINT "PK_c1433d71a4838793a49dcad46ab" PRIMARY KEY ("id"))`);
    await queryRunner.query(`CREATE TABLE "audit_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organization_id" uuid, "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "action" character varying NOT NULL, "resource" character varying NOT NULL, "oldValue" json, "newValue" json, "ipAddress" character varying(100) NOT NULL, "userAgent" character varying(255), "userId" uuid NOT NULL, CONSTRAINT "PK_1bb179d048bbc581caa3b013439" PRIMARY KEY ("id"))`);
    await queryRunner.query(`ALTER TABLE "terms" ADD CONSTRAINT "FK_e47d1cc89d00b393a59aed32b08" FOREIGN KEY ("academicYearId") REFERENCES "academic_years"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "results" ADD CONSTRAINT "FK_c09b15b279d5542d4f130bc4cdb" FOREIGN KEY ("studentId") REFERENCES "students"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "results" ADD CONSTRAINT "FK_3705c1dbfefc01e6be07e7c6b66" FOREIGN KEY ("subjectId") REFERENCES "subjects"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "results" ADD CONSTRAINT "FK_da07d57f43a104a35dbaeeef940" FOREIGN KEY ("assessmentId") REFERENCES "assessments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "assessments" ADD CONSTRAINT "FK_b4f3db3ac8ac27cfb43c70572bd" FOREIGN KEY ("classId") REFERENCES "classes"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "assessments" ADD CONSTRAINT "FK_3d790fa48896e741af9462721cd" FOREIGN KEY ("subjectId") REFERENCES "subjects"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "assessments" ADD CONSTRAINT "FK_6f679feb3816252ba5f579bbeb2" FOREIGN KEY ("academicYearId") REFERENCES "academic_years"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "assessments" ADD CONSTRAINT "FK_69fa5c748abdc2d8e562c4f5b90" FOREIGN KEY ("termId") REFERENCES "terms"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "subjects" ADD CONSTRAINT "FK_3a6b695bdf49370f48274698cf4" FOREIGN KEY ("classId") REFERENCES "classes"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "subjects" ADD CONSTRAINT "FK_09338bca25c0e77ea89989dba1d" FOREIGN KEY ("teacherId") REFERENCES "teachers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "marks" ADD CONSTRAINT "FK_aa9e8312f7ce21846e5e2c3152a" FOREIGN KEY ("studentId") REFERENCES "students"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "marks" ADD CONSTRAINT "FK_dc6d4d61c4c4492c00f20e2bf75" FOREIGN KEY ("subjectId") REFERENCES "subjects"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "marks" ADD CONSTRAINT "FK_879078b7571f23a275a2b162576" FOREIGN KEY ("assessmentId") REFERENCES "assessments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_13e4a61c4496610819d2167ab45" FOREIGN KEY ("feeId") REFERENCES "fees"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_6fe117e5496f6f34b4bd3498ddb" FOREIGN KEY ("processedById") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "fees" ADD CONSTRAINT "FK_4bfe987bde282dde6183efbca51" FOREIGN KEY ("studentId") REFERENCES "students"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "fees" ADD CONSTRAINT "FK_d7db49b4be2de3e2dac4b9232f4" FOREIGN KEY ("feeStructureId") REFERENCES "fee_structures"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "students" ADD CONSTRAINT "FK_e0208b4f964e609959aff431bf9" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "student_enrollments" ADD CONSTRAINT "FK_3a870b3af82db9686a7349b49e7" FOREIGN KEY ("studentId") REFERENCES "students"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "student_enrollments" ADD CONSTRAINT "FK_3dbbb9bd0055eb2e5e6af15ca11" FOREIGN KEY ("classId") REFERENCES "classes"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "teacher_assignments" ADD CONSTRAINT "FK_51c96ca1214fa55d9bec97a2ae2" FOREIGN KEY ("teacherId") REFERENCES "teachers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "teacher_assignments" ADD CONSTRAINT "FK_0d00cb2869f4ca284ef64de11ce" FOREIGN KEY ("classId") REFERENCES "classes"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "teacher_assignments" ADD CONSTRAINT "FK_f0b413bb838d1a0e559a9e180ec" FOREIGN KEY ("subjectId") REFERENCES "subjects"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "teachers" ADD CONSTRAINT "FK_4d8041cbc103a5142fa2f2afad4" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "notification_logs" ADD CONSTRAINT "FK_7f62453355000bdcfa5d5598d48" FOREIGN KEY ("studentId") REFERENCES "students"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "guardian_contacts" ADD CONSTRAINT "FK_edf4cf0eaac2f11027bb0a0bb36" FOREIGN KEY ("studentId") REFERENCES "students"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "marks_correction_requests" ADD CONSTRAINT "FK_9dec887929e9e72f7c93a575b66" FOREIGN KEY ("markId") REFERENCES "marks"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "marks_correction_requests" ADD CONSTRAINT "FK_b8e9f5eb93d8e51fc8aa0cbb4fd" FOREIGN KEY ("requestedById") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "marks_correction_requests" ADD CONSTRAINT "FK_03c535054645f677b206bf87392" FOREIGN KEY ("reviewedById") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "principal_alerts" ADD CONSTRAINT "FK_edffd735b56d3cb7f9364cf2662" FOREIGN KEY ("acknowledgedById") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "report_card_remarks" ADD CONSTRAINT "FK_941ae35780ce934a1a84c596991" FOREIGN KEY ("studentId") REFERENCES "students"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "report_card_remarks" ADD CONSTRAINT "FK_066e6fa8ebb0cf0e341214987d0" FOREIGN KEY ("termId") REFERENCES "terms"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "report_card_remarks" ADD CONSTRAINT "FK_8603994f319ac225e7358c4c09f" FOREIGN KEY ("enteredById") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "sibling_discounts" ADD CONSTRAINT "FK_6e8909e8420009b48d3ce7c6f75" FOREIGN KEY ("studentId") REFERENCES "students"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "fee_fines" ADD CONSTRAINT "FK_f202ea05054c3dbd3c851faeef4" FOREIGN KEY ("feeId") REFERENCES "fees"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "staff_leave_requests" ADD CONSTRAINT "FK_3ac65a6dc7c2a47a1307d8faaa4" FOREIGN KEY ("staffId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "staff_leave_requests" ADD CONSTRAINT "FK_d9a6cee747310a8ac7286e286ce" FOREIGN KEY ("approvedById") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "attendance_records" ADD CONSTRAINT "FK_73dc742eac42ee289715b6d2593" FOREIGN KEY ("sessionId") REFERENCES "attendance_sessions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "attendance_records" ADD CONSTRAINT "FK_21f6cf258d12a2432bd2a8f798d" FOREIGN KEY ("studentId") REFERENCES "students"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "attendance_records" ADD CONSTRAINT "FK_81808fd5719a7f5cb9cd4c770fc" FOREIGN KEY ("markedById") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "attendance_sessions" ADD CONSTRAINT "FK_08c96fa47a130f73457a0fa98e8" FOREIGN KEY ("classId") REFERENCES "classes"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "attendance_sessions" ADD CONSTRAINT "FK_552af4e2a67d864c5210bfcc92e" FOREIGN KEY ("createdById") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "staff_attendance_records" ADD CONSTRAINT "FK_7a0ada2c732d312c768cb51945f" FOREIGN KEY ("staffId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "staff_attendance_records" ADD CONSTRAINT "FK_cd8372802e96a2cf0299a0990cd" FOREIGN KEY ("markedById") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "attendance_correction_requests" ADD CONSTRAINT "FK_ffbe7d168db01963c417bd8e339" FOREIGN KEY ("recordId") REFERENCES "attendance_records"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "attendance_correction_requests" ADD CONSTRAINT "FK_4ae73836836b7d34ec03a0083e0" FOREIGN KEY ("requestedById") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "attendance_correction_requests" ADD CONSTRAINT "FK_18a27e8b3a13fa83001b6724c50" FOREIGN KEY ("reviewedById") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "audit_logs" ADD CONSTRAINT "FK_cfa83f61e4d27a87fcae1e025ab" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`DROP TABLE IF EXISTS "audit_logs" CASCADE`);
    await queryRunner.query(`DROP TABLE IF EXISTS "roles" CASCADE`);
    await queryRunner.query(`DROP TABLE IF EXISTS "attendance_correction_requests" CASCADE`);
    await queryRunner.query(`DROP TABLE IF EXISTS "staff_attendance_records" CASCADE`);
    await queryRunner.query(`DROP TABLE IF EXISTS "attendance_sessions" CASCADE`);
    await queryRunner.query(`DROP TABLE IF EXISTS "attendance_records" CASCADE`);
    await queryRunner.query(`DROP TABLE IF EXISTS "staff_leave_requests" CASCADE`);
    await queryRunner.query(`DROP TABLE IF EXISTS "fee_fines" CASCADE`);
    await queryRunner.query(`DROP TABLE IF EXISTS "sibling_discounts" CASCADE`);
    await queryRunner.query(`DROP TABLE IF EXISTS "report_card_remarks" CASCADE`);
    await queryRunner.query(`DROP TABLE IF EXISTS "principal_alerts" CASCADE`);
    await queryRunner.query(`DROP TABLE IF EXISTS "marks_correction_requests" CASCADE`);
    await queryRunner.query(`DROP TABLE IF EXISTS "guardian_contacts" CASCADE`);
    await queryRunner.query(`DROP TABLE IF EXISTS "notification_logs" CASCADE`);
    await queryRunner.query(`DROP TABLE IF EXISTS "organizations" CASCADE`);
    await queryRunner.query(`DROP TABLE IF EXISTS "teachers" CASCADE`);
    await queryRunner.query(`DROP TABLE IF EXISTS "teacher_assignments" CASCADE`);
    await queryRunner.query(`DROP TABLE IF EXISTS "classes" CASCADE`);
    await queryRunner.query(`DROP TABLE IF EXISTS "student_enrollments" CASCADE`);
    await queryRunner.query(`DROP TABLE IF EXISTS "students" CASCADE`);
    await queryRunner.query(`DROP TABLE IF EXISTS "fees" CASCADE`);
    await queryRunner.query(`DROP TABLE IF EXISTS "payments" CASCADE`);
    await queryRunner.query(`DROP TABLE IF EXISTS "fee_structures" CASCADE`);
    await queryRunner.query(`DROP TABLE IF EXISTS "marks" CASCADE`);
    await queryRunner.query(`DROP TABLE IF EXISTS "subjects" CASCADE`);
    await queryRunner.query(`DROP TABLE IF EXISTS "assessments" CASCADE`);
    await queryRunner.query(`DROP TABLE IF EXISTS "results" CASCADE`);
    await queryRunner.query(`DROP TABLE IF EXISTS "academic_years" CASCADE`);
    await queryRunner.query(`DROP TABLE IF EXISTS "terms" CASCADE`);
    await queryRunner.query(`DROP TABLE IF EXISTS "users" CASCADE`);
  }
}
